In [104]:
!pip list

Package                       Version
----------------------------- --------------------
alabaster                     0.7.12
anaconda-client               1.11.0
anaconda-navigator            2.3.1
anaconda-project              0.11.1
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.2
astroid                       2.11.7
astropy                       5.1
atomicwrites                  1.4.0
attrs                         21.4.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bcrypt                        3.2.0
beautifulsoup4                4.11.1
binaryornot                   0.4.4
bitarray                      2.5.1
bkcharts                      0.2
blac

In [21]:
import numpy as np
import pandas as pd
#import matplotlib.pyplot as plt
import operator
from sklearn.naive_bayes import MultinomialNB
# import matplotlib.pyplot as plt
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import seaborn as sns

In [22]:
# load the data set 
data = pd.read_csv('ccFraud.csv') 
ccdata=data.head(1000000) 
# print info about columns in the dataframe 
print(ccdata.info()) 
ccdata.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 9 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   custID        1000000 non-null  int64
 1   gender        1000000 non-null  int64
 2   state         1000000 non-null  int64
 3   cardholder    1000000 non-null  int64
 4   balance       1000000 non-null  int64
 5   numTrans      1000000 non-null  int64
 6   numIntlTrans  1000000 non-null  int64
 7   creditLine    1000000 non-null  int64
 8   fraudRisk     1000000 non-null  int64
dtypes: int64(9)
memory usage: 68.7 MB
None


custID  gender  state  cardholder  balance  numTrans  numIntlTrans  \
0       1       1     35           1     3000         4            14   
1       2       2      2           1        0         9             0   
2       3       2      2           1        0        27             9   
3       4       1     15           1        0        12             0   
4       5       1     46           1        0        11            16   
5       6       2     44           2     5546        21             0   
6       7       1      3           1     2000        41             0   
7       8       1     10           1     6016        20             3   
8       9       2     32           1     2428         4            10   
9      10       1     23           1        0        18            56   

   creditLine  fraudRisk  
0           2          0  
1          18          0  
2          16          0  
3           5          0  
4           7          0  
5          13          0  
6           1          0  
7           6          0  
8          22          0  
9           5          0

In [23]:
# MODEL MAKING BEGINS - Seperating dependent and independent variables
# Dropping custId column as it autoincrements and no affect on results 
labels = ccdata.columns[1:8]
l1 = ccdata.columns[8]
X = ccdata[labels]
y = ccdata[l1]
print(X)


        gender  state  cardholder  balance  numTrans  numIntlTrans  creditLine
0            1     35           1     3000         4            14           2
1            2      2           1        0         9             0          18
2            2      2           1        0        27             9          16
3            1     15           1        0        12             0           5
4            1     46           1        0        11            16           7
...        ...    ...         ...      ...       ...           ...         ...
999995       2     39           1        0        10            16           3
999996       1     39           1     6000        16             0           5
999997       1     16           1     3000        18             0           2
999998       2     20           1     4716        19             0           4
999999       2      5           1     5443         5             0          22

[1000000 rows x 7 columns]


In [24]:
# split into 70:30 ration 
X_trn, X_tst, y_trn, y_tst = train_test_split(X, y, test_size = 0.4, random_state = 5) 
mg = MultinomialNB()
mg.fit(X_trn, y_trn.ravel())
ypredmg = mg.predict(X_tst)

In [25]:
print(ypredmg)

[1 1 1 ... 0 1 1]


In [26]:
print(confusion_matrix(y_tst,ypredmg))
print(classification_report(y_tst,ypredmg))
amg = accuracy_score(y_tst, ypredmg)
print("Accuracy: %.2f%%" % (amg* 100.0))


[[266322 109664]
 [  7608  16406]]
              precision    recall  f1-score   support

           0       0.97      0.71      0.82    375986
           1       0.13      0.68      0.22     24014

    accuracy                           0.71    400000
   macro avg       0.55      0.70      0.52    400000
weighted avg       0.92      0.71      0.78    400000

Accuracy: 70.68%


In [27]:
print(confusion_matrix(y_tst,ypredmg))
print(classification_report(y_tst,ypredmg))
amg = accuracy_score(y_tst, ypredmg)
print("Accuracy: %.2f%%" % (amg* 100.0))


[[266322 109664]
 [  7608  16406]]
              precision    recall  f1-score   support

           0       0.97      0.71      0.82    375986
           1       0.13      0.68      0.22     24014

    accuracy                           0.71    400000
   macro avg       0.55      0.70      0.52    400000
weighted avg       0.92      0.71      0.78    400000

Accuracy: 70.68%


In [28]:
with open('output.txt') as f:
    content = f.readlines()
# you may also want to remove whitespace characters like `\n` at the end of each line
content = [x.strip() for x in content] 
#content has first name and last name also at index 0 and 1
content2 = []
for i in content[2:]:
 
 content2.append(int(i))
print(content2)

[1, 11, 1, 17656, 16, 3, 25]


In [29]:
xpred = [content2]
#xpred=[[2,11,1,17656,16,3,25]]

pred=mg.predict(xpred)
#pred=1
if (pred==1):
    print("SUSPECTED FRAUD\nWe request the user to remove any kind of obstacles like sungalsses or spectacles for face verification.")
    import face_recognition
    import cv2
    import numpy as np
    from PIL import Image
    import os
    import smtplib, ssl
    import time
    print("Image will be captured automatically at end of 10 seconds. Kindly keep the camera right in front of your face.")
    time.sleep(0.04)
    cmra = cv2.VideoCapture(0)
    dtr=cv2.CascadeClassifier(cv2.data.haarcascades +'haarcascade_frontalface_default.xml')
    sampNum=0
    while(True):
        r, pic = cmra.read()
#         print(r)
#         print(pic)
        gry = cv2.cvtColor(pic, cv2.COLOR_BGR2GRAY)
        fcs = dtr.detectMultiScale(gry, 1.3, 5)
        for (x,y,w,h) in fcs:
            cv2.rectangle(pic,(x,y),(x+w,y+h),(255,0,0),2)
            sampNum=sampNum+1
            cv2.imwrite("dataset/user" + ".jpg", gry[y:y+h,x:x+w])
            cv2.imshow('frame',pic)
        if cv2.waitKey(5) & 0xFF == ord('q'):
            break
        elif sampNum>0:
            break
    cmra.release()
    cv2.destroyAllWindows()
    pic1=face_recognition.load_image_file('./dataset/ref.jpg')
    imgfenc=face_recognition.face_encodings(pic1)[0]
    imgch=face_recognition.load_image_file('./dataset/user.jpg')
    imgfencch=face_recognition.face_encodings(imgch)[0]
    face_recognition.api.face_locations(pic1, number_of_times_to_upsample=1, model='cnn')
    rslt=face_recognition.compare_faces([imgfenc],imgfencch,tolerance=0.6 )
    if rslt[0]:
        print ('PASSED FACE RECOGNITION\nNOW PROCEED NORMALLY')
    else :
        print ('FAILED FACE VERIFICATION\nTHE BANK WOULD BE GETTING IN TOUCH WITH YOU IN FEW SECONDS\nINCONVENIENCE REGRETTED\nTRANSACTION TEMPORARILY PAUSED')
        
else:
    print("LEGAL TRANSACTION... NO SUSPICION\nPROCEED NORMALLY")


C:\Users\prans\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(


SUSPECTED FRAUD
We request the user to remove any kind of obstacles like sungalsses or spectacles for face verification.
Image will be captured automatically at end of 10 seconds. Kindly keep the camera right in front of your face.
PASSED FACE RECOGNITION
NOW PROCEED NORMALLY
